/* CrowRules Sports — Shared Engine 23.0 */
(function(){
"use strict";
const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const HAS_SUPABASE=!!(window.supabase&&typeof window.supabase.createClient==="function");
let sb=null;if(HAS_SUPABASE)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true},global:{headers:{"x-client-info":"crowrules-sports/23.0"}}});
window.sb=sb;window.supabaseClient=sb;window.sbClient=sb;window.CROW_SPORTS_READY=HAS_SUPABASE;window.CROW_SPORTS_VERSION="23.0";window.CROW_SPORTS_SHELL_VERSION="23.0";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function get(k,f=null){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch(_){return f}}function set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){} }
const NAV_GROUPS=[
{label:"GAMES",icon:"◉",items:[["home","HOME","index.html"],["scores","SCORES","scores.html"],["schedule","SCHEDULE","schedule.html"],["live","LIVE","live.html"]]},
{label:"TEAMS",icon:"◆",items:[["teams","TEAMS","teams.html"],["standings","STANDINGS","standings.html"],["rankings","RANKINGS","rankings.html"],["leaders","LEADERS","leaders.html"]]},
{label:"DATA",icon:"▦",items:[["championships","CHAMPIONSHIPS","championships.html"],["championship","CHAMPIONSHIP","championship.html"],["event","EVENT CENTER","event.html"],["sync-health","SYNC HEALTH","sync-health.html"]]},
{label:"MEDIA",icon:"▶",items:[["media","AUDIO / VIDEO","media.html"],["combat","COMBAT / WRESTLING","combat.html"]]},
{label:"COMMUNITY",icon:"✦",items:[["pickem","PICK 'EM","pickem.html"],["notifications","NOTIFICATIONS","notifications.html"],["partners","PARTNERS","partners.html"]]},
{label:"ACCOUNT",icon:"●",items:[["account","MY SPORTS","account.html"]]}
];
const NAV=NAV_GROUPS.flatMap(g=>g.items);function page(){return location.pathname.split("/").pop()||"index.html"}function key(a){if(a)return String(a).replace(/\.html$/i,"").toLowerCase();const m=NAV.find(x=>x[2].toLowerCase()===page().toLowerCase());return m?m[0]:"home"}
function styles(){if($("#cr23-style"))return;const s=document.createElement("style");s.id="cr23-style";s.textContent=`.cr-header{position:sticky;top:0;z-index:9999;background:rgba(5,5,7,.97);border-bottom:1px solid #222;backdrop-filter:blur(16px)}.cr-nav{min-height:60px;display:flex;align-items:center;gap:10px;padding:0 18px}.cr-brand{color:#fff;text-decoration:none;font:900 12px Orbitron,Arial;letter-spacing:1.4px;white-space:nowrap}.cr-brand span{color:#e10600}.cr-links{display:flex;align-items:center;justify-content:flex-end;gap:4px;flex:1}.cr-group{position:relative}.cr-group>button{border:1px solid transparent;background:transparent;color:#aaa;border-radius:8px;padding:10px;font:800 8px Orbitron;cursor:pointer}.cr-group>button:hover,.cr-group.active>button,.cr-group.open>button{color:#fff;background:rgba(225,6,0,.1);border-color:#492020}.cr-menu{position:absolute;right:0;top:calc(100% + 5px);display:none;min-width:180px;padding:6px;background:#08090d;border:1px solid #292929;border-radius:10px;box-shadow:0 18px 45px #000}.cr-group.open .cr-menu{display:flex;flex-direction:column}.cr-menu a{color:#aaa;text-decoration:none;padding:10px;border-radius:7px;font:800 8px Orbitron}.cr-menu a:hover,.cr-menu a.active{color:#fff;background:rgba(225,6,0,.12);box-shadow:inset 2px 0 #e10600}.cr-tools{display:flex;align-items:center;gap:7px}.cr-tool,.cr-league{border:1px solid #292929;background:#0c0c0c;color:#aaa;border-radius:7px;padding:8px 9px;font:800 8px Orbitron;cursor:pointer}.cr-account{max-width:130px;overflow:hidden;text-overflow:ellipsis;color:#aaa;font:700 8px Orbitron}.cr-toggle{display:none;border:1px solid #292929;background:#111;color:#fff;border-radius:8px;padding:9px 11px;font:800 9px Orbitron}.cr-search{border-top:1px solid #222;background:#070707}.cr-search-inner{max-width:1500px;margin:auto;padding:10px 18px}.cr-search input{width:100%;box-sizing:border-box;padding:12px;background:#0d0d0d;border:1px solid #333;color:#fff;font:500 12px Montserrat}.cr-results a{display:block;padding:9px;color:#ccc;text-decoration:none}.cr-results a:hover{background:#151515}.cr-results small{display:block;color:#777;font-size:8px}.cr-results strong{font-size:10px}@media(max-width:1100px){.cr-toggle{display:block}.cr-links{position:absolute;left:8px;right:8px;top:60px;display:none;flex-direction:column;align-items:stretch;background:#08090d;border:1px solid #292929;border-radius:12px;padding:8px;box-shadow:0 20px 50px #000}.cr-links.open{display:flex}.cr-group>button{width:100%;text-align:left}.cr-menu{position:static;box-shadow:none;border:0;background:#101015;margin-bottom:5px}.cr-account{display:none}}@media(max-width:600px){.cr-nav{padding:0 10px}.cr-brand{font-size:10px}}`;document.head.appendChild(s)}
function shell(active){styles();const k=key(active),groups=NAV_GROUPS.map(g=>`<div class="cr-group ${g.items.some(i=>i[0]===k)?"active":""}"><button type="button">${g.icon} ${g.label} ▾</button><div class="cr-menu">${g.items.map(i=>`<a href="${i[2]}" class="${i[0]===k?"active":""}">${i[1]}</a>`).join("")}</div></div>`).join("");document.write(`<header class="cr-header"><nav class="cr-nav"><a class="cr-brand" href="index.html">CROWRULES <span>SPORTS</span></a><div class="cr-links" id="crNavLinks">${groups}</div><div class="cr-tools"><select id="crLeague" class="cr-league" aria-label="League"><option value="all">ALL SPORTS</option><option>NFL</option><option>MLB</option><option>NBA</option><option>WNBA</option><option>NHL</option><option>MLS</option><option>NCAA</option><option>WWE</option><option>AEW</option><option>UFC</option></select><button class="cr-tool" id="crSearchToggle" type="button">SEARCH</button><button class="cr-toggle" id="crMenuToggle" type="button">MENU</button><span class="cr-account" id="crAccount">GUEST</span></div></nav><div class="cr-search" id="crSearch" hidden><div class="cr-search-inner"><input id="crSearchInput" placeholder="Search Sports…" autocomplete="off"><div class="cr-results" id="crResults"></div></div></div></header>`);setTimeout(init,0)}
function init(){const links=$("#crNavLinks"),toggle=$("#crMenuToggle"),search=$("#crSearch"),searchBtn=$("#crSearchToggle"),input=$("#crSearchInput"),results=$("#crResults"),league=$("#crLeague");if(!links)return;league.value=get("cr_sports_league","all");league.addEventListener("change",()=>{set("cr_sports_league",league.value);window.CROW_SPORTS_LEAGUE=league.value;document.dispatchEvent(new CustomEvent("crowrules:leaguechange",{detail:{league:league.value}}))});toggle.addEventListener("click",()=>links.classList.toggle("open"));links.querySelectorAll(".cr-group>button").forEach(b=>b.addEventListener("click",()=>{const g=b.parentElement;links.querySelectorAll(".cr-group.open").forEach(x=>x!==g&&x.classList.remove("open"));g.classList.toggle("open")}));document.addEventListener("click",e=>{if(!e.target.closest(".cr-nav"))links.querySelectorAll(".cr-group.open").forEach(g=>g.classList.remove("open"))});searchBtn.addEventListener("click",()=>{search.hidden=!search.hidden;if(!search.hidden)input.focus()});function render(q){const t=q.trim().toLowerCase(),rows=t?NAV.filter(x=>x[1].toLowerCase().includes(t)):NAV.slice(0,8);results.innerHTML=rows.map(x=>`<a href="${x[2]}"><small>PAGE</small><strong>${esc(x[1])}</strong></a>`).join("")}input.addEventListener("input",()=>render(input.value));render("");updateAccount()}
async function updateAccount(){const el=$("#crAccount");if(!el)return;if(!sb){el.textContent="GUEST";return}try{const{data}=await sb.auth.getSession();el.textContent=data?.session?.user?.email||"GUEST"}catch(_){el.textContent="GUEST"}}
window.loadSession=window.loadSession||updateAccount;window.shell=shell;window.footer=window.footer||function(){};window.$=$;window.esc=esc;
})();
